/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as TestOnboardRouteImport } from './routes/test/onboard'
import { Route as TestCvRouteImport } from './routes/test/cv'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as OauthMicrosoftRouteImport } from './routes/oauth/microsoft'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DocumentWebhook_documentRouteImport } from './routes/_document/webhook_document'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppComparefile_testRouteImport } from './routes/_app/comparefile_test'
import { Route as AppChangePasswordRouteImport } from './routes/_app/change-password'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects/$id/index'
import { Route as AppRoleIndexRouteImport } from './routes/_app/role/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app/employees/index'
import { Route as ProjectsIdRolesRouteImport } from './routes/projects/$id/roles'
import { Route as ProjectsIdEmployeesRouteImport } from './routes/projects/$id/employees'
import { Route as ProjectsIdEditRouteImport } from './routes/projects/$id/edit'
import { Route as AppRolePartnersRouteImport } from './routes/_app/role/partners'
import { Route as AppRoleEmployeesRouteImport } from './routes/_app/role/employees'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as AppHrApproveRouteImport } from './routes/_app/hr.approve'
import { Route as AppEmployeesNewRouteImport } from './routes/_app/employees/new'
import { Route as AppEmployeesIdRouteImport } from './routes/_app/employees/$id'
import { Route as ProjectsIdEmployeesNewRouteImport } from './routes/projects/$id/employees.new'
import { Route as AppDeveloperIdWebhooksRouteImport } from './routes/_app/developer/$id/webhooks'

const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TestOnboardRoute = TestOnboardRouteImport.update({
  id: '/test/onboard',
  path: '/test/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCvRoute = TestCvRouteImport.update({
  id: '/test/cv',
  path: '/test/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthMicrosoftRoute = OauthMicrosoftRouteImport.update({
  id: '/oauth/microsoft',
  path: '/oauth/microsoft',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentWebhook_documentRoute =
  DocumentWebhook_documentRouteImport.update({
    id: '/_document/webhook_document',
    path: '/webhook_document',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppComparefile_testRoute = AppComparefile_testRouteImport.update({
  id: '/comparefile_test',
  path: '/comparefile_test',
  getParentRoute: () => AppRoute,
} as any)
const AppChangePasswordRoute = AppChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AppRoute,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const AppRoleIndexRoute = AppRoleIndexRouteImport.update({
  id: '/role/',
  path: '/role/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const ProjectsIdRolesRoute = ProjectsIdRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdEmployeesRoute = ProjectsIdEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const AppRolePartnersRoute = AppRolePartnersRouteImport.update({
  id: '/role/partners',
  path: '/role/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleEmployeesRoute = AppRoleEmployeesRouteImport.update({
  id: '/role/employees',
  path: '/role/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppHrApproveRoute = AppHrApproveRouteImport.update({
  id: '/hr/approve',
  path: '/hr/approve',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesNewRoute = AppEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const ProjectsIdEmployeesNewRoute = ProjectsIdEmployeesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsIdEmployeesRoute,
} as any)
const AppDeveloperIdWebhooksRoute = AppDeveloperIdWebhooksRouteImport.update({
  id: '/developer/$id/webhooks',
  path: '/developer/$id/webhooks',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/coming-soon': typeof ComingSoonRoute
  '/shared': typeof SharedRoute
  '/change-password': typeof AppChangePasswordRoute
  '/comparefile_test': typeof AppComparefile_testRoute
  '/profile': typeof AppProfileRoute
  '/webhook_document': typeof DocumentWebhook_documentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/oauth/microsoft': typeof OauthMicrosoftRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/test/cv': typeof TestCvRoute
  '/test/onboard': typeof TestOnboardRoute
  '/': typeof AppIndexRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/employees/new': typeof AppEmployeesNewRoute
  '/hr/approve': typeof AppHrApproveRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/role/employees': typeof AppRoleEmployeesRoute
  '/role/partners': typeof AppRolePartnersRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/employees': typeof ProjectsIdEmployeesRouteWithChildren
  '/projects/$id/roles': typeof ProjectsIdRolesRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/role': typeof AppRoleIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/developer/$id/webhooks': typeof AppDeveloperIdWebhooksRoute
  '/projects/$id/employees/new': typeof ProjectsIdEmployeesNewRoute
}
export interface FileRoutesByTo {
  '/coming-soon': typeof ComingSoonRoute
  '/shared': typeof SharedRoute
  '/change-password': typeof AppChangePasswordRoute
  '/comparefile_test': typeof AppComparefile_testRoute
  '/profile': typeof AppProfileRoute
  '/webhook_document': typeof DocumentWebhook_documentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/oauth/microsoft': typeof OauthMicrosoftRoute
  '/test/cv': typeof TestCvRoute
  '/test/onboard': typeof TestOnboardRoute
  '/': typeof AppIndexRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/employees/new': typeof AppEmployeesNewRoute
  '/hr/approve': typeof AppHrApproveRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/role/employees': typeof AppRoleEmployeesRoute
  '/role/partners': typeof AppRolePartnersRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/employees': typeof ProjectsIdEmployeesRouteWithChildren
  '/projects/$id/roles': typeof ProjectsIdRolesRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/role': typeof AppRoleIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/developer/$id/webhooks': typeof AppDeveloperIdWebhooksRoute
  '/projects/$id/employees/new': typeof ProjectsIdEmployeesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/shared': typeof SharedRoute
  '/_app/change-password': typeof AppChangePasswordRoute
  '/_app/comparefile_test': typeof AppComparefile_testRoute
  '/_app/profile': typeof AppProfileRoute
  '/_document/webhook_document': typeof DocumentWebhook_documentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/oauth/microsoft': typeof OauthMicrosoftRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/test/cv': typeof TestCvRoute
  '/test/onboard': typeof TestOnboardRoute
  '/_app/': typeof AppIndexRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/employees/new': typeof AppEmployeesNewRoute
  '/_app/hr/approve': typeof AppHrApproveRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/role/employees': typeof AppRoleEmployeesRoute
  '/_app/role/partners': typeof AppRolePartnersRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/employees': typeof ProjectsIdEmployeesRouteWithChildren
  '/projects/$id/roles': typeof ProjectsIdRolesRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/role/': typeof AppRoleIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/_app/developer/$id/webhooks': typeof AppDeveloperIdWebhooksRoute
  '/projects/$id/employees/new': typeof ProjectsIdEmployeesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/coming-soon'
    | '/shared'
    | '/change-password'
    | '/comparefile_test'
    | '/profile'
    | '/webhook_document'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/oauth/microsoft'
    | '/projects/$id'
    | '/test/cv'
    | '/test/onboard'
    | '/'
    | '/employees/$id'
    | '/employees/new'
    | '/hr/approve'
    | '/projects/new'
    | '/role/employees'
    | '/role/partners'
    | '/projects/$id/edit'
    | '/projects/$id/employees'
    | '/projects/$id/roles'
    | '/employees'
    | '/projects'
    | '/role'
    | '/projects/$id/'
    | '/developer/$id/webhooks'
    | '/projects/$id/employees/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/coming-soon'
    | '/shared'
    | '/change-password'
    | '/comparefile_test'
    | '/profile'
    | '/webhook_document'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/oauth/microsoft'
    | '/test/cv'
    | '/test/onboard'
    | '/'
    | '/employees/$id'
    | '/employees/new'
    | '/hr/approve'
    | '/projects/new'
    | '/role/employees'
    | '/role/partners'
    | '/projects/$id/edit'
    | '/projects/$id/employees'
    | '/projects/$id/roles'
    | '/employees'
    | '/projects'
    | '/role'
    | '/projects/$id'
    | '/developer/$id/webhooks'
    | '/projects/$id/employees/new'
  id:
    | '__root__'
    | '/_app'
    | '/coming-soon'
    | '/shared'
    | '/_app/change-password'
    | '/_app/comparefile_test'
    | '/_app/profile'
    | '/_document/webhook_document'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/oauth/microsoft'
    | '/projects/$id'
    | '/test/cv'
    | '/test/onboard'
    | '/_app/'
    | '/_app/employees/$id'
    | '/_app/employees/new'
    | '/_app/hr/approve'
    | '/_app/projects/new'
    | '/_app/role/employees'
    | '/_app/role/partners'
    | '/projects/$id/edit'
    | '/projects/$id/employees'
    | '/projects/$id/roles'
    | '/_app/employees/'
    | '/_app/projects/'
    | '/_app/role/'
    | '/projects/$id/'
    | '/_app/developer/$id/webhooks'
    | '/projects/$id/employees/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ComingSoonRoute: typeof ComingSoonRoute
  SharedRoute: typeof SharedRoute
  DocumentWebhook_documentRoute: typeof DocumentWebhook_documentRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  OauthMicrosoftRoute: typeof OauthMicrosoftRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  TestCvRoute: typeof TestCvRoute
  TestOnboardRoute: typeof TestOnboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/test/onboard': {
      id: '/test/onboard'
      path: '/test/onboard'
      fullPath: '/test/onboard'
      preLoaderRoute: typeof TestOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/cv': {
      id: '/test/cv'
      path: '/test/cv'
      fullPath: '/test/cv'
      preLoaderRoute: typeof TestCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/microsoft': {
      id: '/oauth/microsoft'
      path: '/oauth/microsoft'
      fullPath: '/oauth/microsoft'
      preLoaderRoute: typeof OauthMicrosoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_document/webhook_document': {
      id: '/_document/webhook_document'
      path: '/webhook_document'
      fullPath: '/webhook_document'
      preLoaderRoute: typeof DocumentWebhook_documentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comparefile_test': {
      id: '/_app/comparefile_test'
      path: '/comparefile_test'
      fullPath: '/comparefile_test'
      preLoaderRoute: typeof AppComparefile_testRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/change-password': {
      id: '/_app/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AppChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/_app/role/': {
      id: '/_app/role/'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof AppRoleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/projects/$id/roles': {
      id: '/projects/$id/roles'
      path: '/roles'
      fullPath: '/projects/$id/roles'
      preLoaderRoute: typeof ProjectsIdRolesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/employees': {
      id: '/projects/$id/employees'
      path: '/employees'
      fullPath: '/projects/$id/employees'
      preLoaderRoute: typeof ProjectsIdEmployeesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/_app/role/partners': {
      id: '/_app/role/partners'
      path: '/role/partners'
      fullPath: '/role/partners'
      preLoaderRoute: typeof AppRolePartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/role/employees': {
      id: '/_app/role/employees'
      path: '/role/employees'
      fullPath: '/role/employees'
      preLoaderRoute: typeof AppRoleEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/approve': {
      id: '/_app/hr/approve'
      path: '/hr/approve'
      fullPath: '/hr/approve'
      preLoaderRoute: typeof AppHrApproveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/new': {
      id: '/_app/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AppEmployeesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/projects/$id/employees/new': {
      id: '/projects/$id/employees/new'
      path: '/new'
      fullPath: '/projects/$id/employees/new'
      preLoaderRoute: typeof ProjectsIdEmployeesNewRouteImport
      parentRoute: typeof ProjectsIdEmployeesRoute
    }
    '/_app/developer/$id/webhooks': {
      id: '/_app/developer/$id/webhooks'
      path: '/developer/$id/webhooks'
      fullPath: '/developer/$id/webhooks'
      preLoaderRoute: typeof AppDeveloperIdWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChangePasswordRoute: typeof AppChangePasswordRoute
  AppComparefile_testRoute: typeof AppComparefile_testRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppEmployeesNewRoute: typeof AppEmployeesNewRoute
  AppHrApproveRoute: typeof AppHrApproveRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppRoleEmployeesRoute: typeof AppRoleEmployeesRoute
  AppRolePartnersRoute: typeof AppRolePartnersRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppRoleIndexRoute: typeof AppRoleIndexRoute
  AppDeveloperIdWebhooksRoute: typeof AppDeveloperIdWebhooksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChangePasswordRoute: AppChangePasswordRoute,
  AppComparefile_testRoute: AppComparefile_testRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppEmployeesNewRoute: AppEmployeesNewRoute,
  AppHrApproveRoute: AppHrApproveRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppRoleEmployeesRoute: AppRoleEmployeesRoute,
  AppRolePartnersRoute: AppRolePartnersRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppRoleIndexRoute: AppRoleIndexRoute,
  AppDeveloperIdWebhooksRoute: AppDeveloperIdWebhooksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProjectsIdEmployeesRouteChildren {
  ProjectsIdEmployeesNewRoute: typeof ProjectsIdEmployeesNewRoute
}

const ProjectsIdEmployeesRouteChildren: ProjectsIdEmployeesRouteChildren = {
  ProjectsIdEmployeesNewRoute: ProjectsIdEmployeesNewRoute,
}

const ProjectsIdEmployeesRouteWithChildren =
  ProjectsIdEmployeesRoute._addFileChildren(ProjectsIdEmployeesRouteChildren)

interface ProjectsIdRouteChildren {
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
  ProjectsIdEmployeesRoute: typeof ProjectsIdEmployeesRouteWithChildren
  ProjectsIdRolesRoute: typeof ProjectsIdRolesRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdEditRoute: ProjectsIdEditRoute,
  ProjectsIdEmployeesRoute: ProjectsIdEmployeesRouteWithChildren,
  ProjectsIdRolesRoute: ProjectsIdRolesRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ComingSoonRoute: ComingSoonRoute,
  SharedRoute: SharedRoute,
  DocumentWebhook_documentRoute: DocumentWebhook_documentRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  OauthMicrosoftRoute: OauthMicrosoftRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  TestCvRoute: TestCvRoute,
  TestOnboardRoute: TestOnboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
