/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableRouteImport } from './routes/table'
import { Route as RoleRouteImport } from './routes/role'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PermissionRouteImport } from './routes/permission'
import { Route as NewRouteImport } from './routes/new'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthMicrosoftRouteImport } from './routes/oauth/microsoft'
import { Route as EmployeeIdRouteImport } from './routes/employee.$id'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionRoute = PermissionRouteImport.update({
  id: '/permission',
  path: '/permission',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthMicrosoftRoute = OauthMicrosoftRouteImport.update({
  id: '/oauth/microsoft',
  path: '/oauth/microsoft',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIdRoute = EmployeeIdRouteImport.update({
  id: '/employee/$id',
  path: '/employee/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/new': typeof NewRoute
  '/permission': typeof PermissionRoute
  '/projects': typeof ProjectsRoute
  '/role': typeof RoleRoute
  '/table': typeof TableRoute
  '/auth/login': typeof AuthLoginRoute
  '/employee/$id': typeof EmployeeIdRoute
  '/oauth/microsoft': typeof OauthMicrosoftRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/new': typeof NewRoute
  '/permission': typeof PermissionRoute
  '/projects': typeof ProjectsRoute
  '/role': typeof RoleRoute
  '/table': typeof TableRoute
  '/auth/login': typeof AuthLoginRoute
  '/employee/$id': typeof EmployeeIdRoute
  '/oauth/microsoft': typeof OauthMicrosoftRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/new': typeof NewRoute
  '/permission': typeof PermissionRoute
  '/projects': typeof ProjectsRoute
  '/role': typeof RoleRoute
  '/table': typeof TableRoute
  '/auth/login': typeof AuthLoginRoute
  '/employee/$id': typeof EmployeeIdRoute
  '/oauth/microsoft': typeof OauthMicrosoftRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/employees'
    | '/new'
    | '/permission'
    | '/projects'
    | '/role'
    | '/table'
    | '/auth/login'
    | '/employee/$id'
    | '/oauth/microsoft'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/employees'
    | '/new'
    | '/permission'
    | '/projects'
    | '/role'
    | '/table'
    | '/auth/login'
    | '/employee/$id'
    | '/oauth/microsoft'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/employees'
    | '/new'
    | '/permission'
    | '/projects'
    | '/role'
    | '/table'
    | '/auth/login'
    | '/employee/$id'
    | '/oauth/microsoft'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  EmployeesRoute: typeof EmployeesRoute
  NewRoute: typeof NewRoute
  PermissionRoute: typeof PermissionRoute
  ProjectsRoute: typeof ProjectsRoute
  RoleRoute: typeof RoleRoute
  TableRoute: typeof TableRoute
  EmployeeIdRoute: typeof EmployeeIdRoute
  OauthMicrosoftRoute: typeof OauthMicrosoftRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permission': {
      id: '/permission'
      path: '/permission'
      fullPath: '/permission'
      preLoaderRoute: typeof PermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/microsoft': {
      id: '/oauth/microsoft'
      path: '/oauth/microsoft'
      fullPath: '/oauth/microsoft'
      preLoaderRoute: typeof OauthMicrosoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$id': {
      id: '/employee/$id'
      path: '/employee/$id'
      fullPath: '/employee/$id'
      preLoaderRoute: typeof EmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  EmployeesRoute: EmployeesRoute,
  NewRoute: NewRoute,
  PermissionRoute: PermissionRoute,
  ProjectsRoute: ProjectsRoute,
  RoleRoute: RoleRoute,
  TableRoute: TableRoute,
  EmployeeIdRoute: EmployeeIdRoute,
  OauthMicrosoftRoute: OauthMicrosoftRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
